server:
  port: 8181
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://150.158.55.26:3366/bms?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
redis:
  host: 127.0.0.1
  port: 6379
  database: 0
  jedis:
    pool:
      max-active: -1
      max-wait: 3000
      max-idle: 20
      min-idle: 2
